#ifndef LIBRARIES_ASM_RISCV_RISCVASSEMBLERCOMMAND_HPP_
#define LIBRARIES_ASM_RISCV_RISCVASSEMBLERCOMMAND_HPP_

class RISCVAssemblerCommand {

};

#endif //LIBRARIES_ASM_RISCV_RISCVASSEMBLERCOMMAND_HPP_
