#ifndef LIBRARIES_ASM_RISCV_RISCVASSEMBLERTOBINARY_HPP_
#define LIBRARIES_ASM_RISCV_RISCVASSEMBLERTOBINARY_HPP_

class RISCVAssemblerToBinary {

};

#endif //LIBRARIES_ASM_RISCV_RISCVASSEMBLERTOBINARY_HPP_
